In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
listings = pd.read_csv('listings_berlin_details.csv.gz')
pd.set_option('display.max_columns', None)
listings.head(5)

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2015,https://www.airbnb.com/rooms/2015,20211217003618,2021-12-17,Berlin-Mitte Value! Quiet courtyard/very central,Great location! <br />30 of 75 sq meters. Thi...,It is located in the former East Berlin area o...,https://a0.muscache.com/pictures/260fd609-710a...,2217,https://www.airbnb.com/users/show/2217,Ion,2008-08-18,"Key Biscayne, Florida, United States",Isn’t sharing economy great?,within an hour,96%,91%,t,https://a0.muscache.com/im/pictures/user/21428...,https://a0.muscache.com/im/pictures/user/21428...,Mitte,5.0,5.0,['email'],t,f,"Berlin, Germany",Brunnenstr. Süd,Mitte,52.53305,13.40394,Entire guesthouse,Entire home/apt,2,NaN,1 bath,1.0,2.0,"[""Essentials"", ""Heating"", ""Backyard"", ""Long te...",$53.00,90,1125,2.0,90.0,1125.0,1125.0,84.3,1125.0,NaN,t,28,58,64,326,2021-12-17,144,10,0,2016-04-11,2021-11-02,4.66,4.79,4.52,4.88,4.90,4.96,4.58,NaN,f,4,4,0,0,2.08
1,3176,https://www.airbnb.com/rooms/3176,20211217003618,2021-12-17,Fabulous Flat in great Location,This beautiful first floor apartment is situa...,The neighbourhood is famous for its variety of...,https://a0.muscache.com/pictures/243355/84afcf...,3718,https://www.airbnb.com/users/show/3718,Britta,2008-10-19,"Coledale, New South Wales, Australia",We love to travel ourselves a lot and prefer t...,NaN,NaN,100%,f,https://a0.muscache.com/im/users/3718/profile_...,https://a0.muscache.com/im/users/3718/profile_...,Prenzlauer Berg,1.0,1.0,"['email', 'phone', 'facebook', 'reviews', 'man...",t,t,"Berlin, Germany",Prenzlauer Berg Südwest,Pankow,52.53471,13.41810,Entire rental unit,Entire home/apt,4,NaN,1 bath,1.0,2.0,"[""Essentials"", ""Heating"", ""Smoke alarm"", ""Iron...",$90.00,92,1125,92.0,92.0,1125.0,1125.0,92.0,1125.0,NaN,t,0,0,0,170,2021-12-17,147,1,0,2009-06-20,2021-01-01,4.63,4.68,4.53,4.64,4.69,4.92,4.63,NaN,f,1,1,0,0,0.97
2,7071,https://www.airbnb.com/rooms/7071,20211217003618,2021-12-17,BrightRoom with sunny greenview!,Cozy and large room in the beautiful district ...,"Great neighborhood with plenty of Cafés, Baker...",https://a0.muscache.com/pictures/21278/32a1622...,17391,https://www.airbnb.com/users/show/17391,BrightRoom,2009-05-16,"Berlin, Berlin, Germany",I am easy going and love making new friends! I...,NaN,NaN,NaN,t,https://a0.muscache.com/im/pictures/user/48c3d...,https://a0.muscache.com/im/pictures/user/48c3d...,Prenzlauer Berg,2.0,2.0,"['email', 'phone', 'reviews', 'jumio', 'govern...",t,t,"Berlin, Germany",Helmholtzplatz,Pankow,52.54301,13.41534,Private room in rental unit,Private room,2,NaN,1 shared bath,1.0,2.0,"[""Essentials"", ""Heating"", ""Refrigerator"", ""Hai...",$33.00,1,10,1.0,1.0,10.0,10.0,1.0,10.0,NaN,t,0,0,0,0,2021-12-17,293,0,0,2009-08-18,2020-03-31,4.83,4.85,4.90,4.86,4.85,4.91,4.71,NaN,t,1,0,1,0,1.95
3,9991,https://www.airbnb.com/rooms/9991,20211217003618,2021-12-17,Geourgeous flat - outstanding views,4 bedroom with very large windows and outstand...,Prenzlauer Berg is an amazing neighbourhood wh...,https://a0.muscache.com/pictures/42799131/59c8...,33852,https://www.airbnb.com/users/show/33852,Philipp,2009-08-25,"Berlin, Berlin, Germany",Born in Munich - lives in and loves Berlin. Wo...,NaN,NaN,0%,f,https://a0.muscache.com/im/users/33852/profile...,https://a0.muscache.com/im/users/33852/profile...,Prenzlauer Berg,1.0,1.0,['email'],t,t,"Berlin, Germany",Prenzlauer Berg Südwest,Pankow,52.53269,13.41805,Entire rental unit,Entire home/apt,7,NaN,2.5 baths,4.0,7.0,"[""Essentials"", ""Children\u2019s dinnerware"", ""...",$180.00,6,14,6.0,6.0,14.0,14.0,6.0,14.0,NaN,t,0,0,0,0,2021-12-17,8,0,0,2015-08-09,2020-01-04,5.00,5.00,5.00,5.00,5.00,4.86,4.86,03/Z/RA/003410-18,f,1,1,0,0,0.10
4,14325,https://www.airbnb.com/rooms/14325,20211217003618,2021-12-17,Apartment in Prenzlauer Berg,The apartment is located on the upper second f...,NaN,https://a0.muscache.com/pictures/508703/24988a...,55531,https://www.airbnb.com/users/show/55531,Chris + Oliver,2009-11-18,"Berlin, Berlin, Germany","From Berlin, Germany. We love to travel!",within a day,67%,44%,t,https://a0.muscache.com/im/users/55531/profile...,https://a0.muscache.com/im/users/55531/profile...,Prenzlauer Berg,4.0,4.0,"['email', 'work_email']",t,t,NaN,Prenzlauer Berg Nordwest,Pankow,52.54813,13.40366,Entire rental unit,Entire home/apt,1,NaN,1 bath,NaN,1.0,"[""Ethernet connection"", ""Heating"", ""Coffee mak...",$70.00,95,1125,95.0,95.0,1125.0,1125.0,95.0,1125.0,NaN,t,19,19,19,159,2021-12-17,26,1,0,2010-06-29,2021-06-21,4.67,5.00,4.84,4.68,4.84,4.58,4.42,NaN,f,3,3,0,0,0.19

In [3]:
listings.shape

(17290, 74)

## filter the data: no reviews, hotels category

In [4]:
listings_filtered=listings.copy()

In [5]:
#exclude new listings (dont have any reviews), if they are not in use we dont use them
listings_filtered=listings_filtered[listings_filtered['number_of_reviews']>0]
listings_filtered.shape

(14042, 74)

In [6]:
#exlude those listing which are obviously professional listings
#room_type=hotel room
listings_filtered.room_type.value_counts()

Entire home/apt    8062
Private room       5702
Shared room         158
Hotel room          120
Name: room_type, dtype: int64

In [7]:
#exclude hotel room (just a few)
listings_filtered=listings_filtered[listings_filtered['room_type']!='Hotel room']
listings_filtered.shape

(13922, 74)

In [8]:
listings_filtered = listings_filtered.reset_index(drop=True)

## NaN values

In [9]:
nulls_percent_df = pd.DataFrame(listings_filtered.isna().sum()/len(listings_filtered)).reset_index()
nulls_percent_df.columns = ['column_name', 'nulls_percentage']
nulls_percent_df.T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73
column_name,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
nulls_percentage,0.0,0.0,0.0,0.0,0.001077,0.019466,0.437653,0.0,0.0,0.0,0.000431,0.000431,0.002227,0.481396,0.513504,0.513504,0.445554,0.000431,0.000431,0.000431,0.30635,0.000431,0.000431,0.0,0.000431,0.000431,0.437581,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000575,0.081166,0.01609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.021836,0.021692,0.022698,0.021908,0.022626,0.02277,0.739836,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
#some columns with Nans can be dropped because they are not relevant:
# name of listing, description of listing, all bathrooms values are Nan, ...
drop_list=['name','description','neighborhood_overview','host_about','bathrooms','calendar_updated','license','host_acceptance_rate','host_neighbourhood','neighbourhood']

In [11]:
#look closer into those:

#host location, host response_time,host_response_rate,,host_neighbourhood,neighbourhood,bathrooms_text,
#bedrooms, beds
#look into all review scores

### host_location: deal with NaNs and optimize column values

In [12]:
listings_filtered.host_location.value_counts(dropna=False)

Berlin, Berlin, Germany                         10910
DE                                               1065
Germany                                           182
Munich, Bavaria, Germany                           74
Hamburg, Hamburg, Germany                          63
                                                ...
São Paulo, State of São Paulo, Brazil               1
San Miguel de Tucuman, Tucumán, Argentina           1
Bonn, North Rhine-Westphalia, Germany               1
Zweibrücken, Rhineland-Palatinate, Germany          1
Petershagen/Eggersdorf, Brandenburg, Germany        1
Name: host_location, Length: 775, dtype: int64

In [13]:
listings_filtered['host_location'].isnull().sum()

31

In [14]:
#drop those two listings
listings_filtered.dropna(subset = ["host_location"], inplace=True)

In [15]:
#i would change this column to: host is from germany or not
#and if from germany from berlin or not

In [16]:
#get a boolean if host is from germany or not
germany=listings_filtered['host_location'].str.contains("Germany|DE", case=False)

In [17]:
#look at those who are false to verify
listings_filtered['host_location'][germany==False].head(50)

0                   Key Biscayne, Florida, United States
1                   Coledale, New South Wales, Australia
5                  Santa Cruz, California, United States
8                  Santa Cruz, California, United States
28                   Port Douglas, Queensland, Australia
42                        Ibiza, Balearic Islands, Spain
44                       Atlanta, Georgia, United States
63                  Overland Park, Kansas, United States
86                                          Japan, Tokyo
162                       Palmview, Texas, United States
163                           Barcelona, Cataluña, Spain
169                                   Oslo, Oslo, Norway
202                               Athens, Attica, Greece
220                       Ibiza, Balearic Islands, Spain
221                          Riomaggiore, Liguria, Italy
229                             Montreal, Quebec, Canada
262                            Windhoek, Khomas, Namibia
267                       Palma, Balearic Islands, Spain
272                                               London
311                                     Tel Aviv, Israel
316                       Selva, Balearic Islands, Spain
317                        El Paso, Texas, United States
359                                        United States
373                          Zurich, Zurich, Switzerland
390                               London, United Kingdom
439                   Madrid, Community of Madrid, Spain
449                                             Tel Aviv
459           Prague, Hlavní město Praha, Czech Republic
468                                Verona, Veneto, Italy
482              Greater London, England, United Kingdom
504                                               Israel
528             Tel Aviv-Yafo, Tel Aviv District, Israel
529             Tel Aviv-Yafo, Tel Aviv District, Israel
583                               Milan, Lombardy, Italy
587             Tel Aviv-Yafo, Tel Aviv District, Israel
599                          Barcelona, Catalonia, Spain
641                   Madrid, Community of Madrid, Spain
659             San Francisco, California, United States
660               Los Angeles, California, United States
689                             Rennes, Brittany, France
733                    New York, New York, United States
735                         Embrach, Zurich, Switzerland
741                  Vancouver, British Columbia, Canada
750                          Zürich, Zürich, Switzerland
761                               London, United Kingdom
764                          Brussels, Brussels, Belgium
781                     Tijuana, Baja California, Mexico
785                          Geneva, Geneva, Switzerland
808                                               London
817    Objat, Aquitaine-Limousin-Poitou-Charentes, Fr...
Name: host_location, dtype: object

In [18]:
#look at those who are false to verify
listings_filtered['host_location'][germany==False].tail(50)

13206                Oxford, England, United Kingdom
13238           Untersiggenthal, Aargau, Switzerland
13260                Oxford, England, United Kingdom
13277                Oxford, England, United Kingdom
13323                                             AR
13327                Ankara, Ankara Province, Turkey
13333                                             FR
13336             Dubai, Dubai, United Arab Emirates
13345                                             GB
13353                   São Paulo, São Paulo, Brazil
13356                                             FI
13367                     Strasbourg, Alsace, France
13425                      Bogota, Bolivar, Colombia
13426                                             AR
13429                     Iași, Iași County, Romania
13433                London, England, United Kingdom
13449          Champagne, Nouvelle-Aquitaine, France
13476       San Francisco, California, United States
13510           Valencia, Valencian Community, Spain
13517              New York, New York, United States
13524                       Lisbon, Lisbon, Portugal
13535             Madrid, Community of Madrid, Spain
13539                                             FR
13544         Los Angeles, California, United States
13555                    El Masnou, Catalunya, Spain
13584     Saint Petersburg, Saint Petersburg, Russia
13587                      Bogota, Bolivar, Colombia
13589       San Francisco, California, United States
13592                    Tarragona, Catalonia, Spain
13628                                             RO
13680                                             CL
13694    Luxembourg, Luxembourg District, Luxembourg
13712                         Gijón, Asturias, Spain
13724                                  United States
13739                                             ES
13762                     Hermosillo, Sonora, Mexico
13777                                             GB
13778                        Naples, Campania, Italy
13789     Saint Petersburg, Saint Petersburg, Russia
13800                                             JO
13812                                             ES
13827                                             AE
13837                                             GB
13838                                             GB
13839                                             GB
13840                                             GB
13842                        Milan, Lombardia, Italy
13843                                      Singapore
13911                                Zagreb, Croatia
13912              Brooklyn, New York, United States
Name: host_location, dtype: object

In [19]:
germany.value_counts() #most of them from germany

True     12994
False      897
Name: host_location, dtype: int64

In [20]:
listings_filtered['Host_location_germany']=germany

In [21]:
#get a boolean if host is from Berlin or not
berlin=listings_filtered['host_location'].str.contains("Berlin", case=False)
berlin

0        False
1        False
2         True
3         True
4         True
         ...
13917     True
13918     True
13919    False
13920     True
13921    False
Name: host_location, Length: 13891, dtype: bool

In [22]:
berlin.value_counts() #most of them from are from berlin

True     10956
False     2935
Name: host_location, dtype: int64

In [23]:
listings_filtered['host_location'][berlin==False].head(50)

0                 Key Biscayne, Florida, United States
1                 Coledale, New South Wales, Australia
5                Santa Cruz, California, United States
6      Rio de Janeiro, State of Rio de Janeiro, Brazil
7                            Hamburg, Hamburg, Germany
8                Santa Cruz, California, United States
28                 Port Douglas, Queensland, Australia
42                      Ibiza, Balearic Islands, Spain
43                      Wandlitz, Brandenburg, Germany
44                     Atlanta, Georgia, United States
56                                             Germany
63                Overland Park, Kansas, United States
86                                        Japan, Tokyo
110        Bad Salzuflen, Nordrhein-Westfalen, Germany
129           Buenos Aires, Capital Federal, Argentina
162                     Palmview, Texas, United States
163                         Barcelona, Cataluña, Spain
169                                 Oslo, Oslo, Norway
184                      Gransee, Brandenburg, Germany
185                      Gransee, Brandenburg, Germany
202                             Athens, Attica, Greece
219                            Munich, Bayern, Germany
220                     Ibiza, Balearic Islands, Spain
221                        Riomaggiore, Liguria, Italy
229                           Montreal, Quebec, Canada
230                                            Germany
232                                            Germany
245                            Munich, Bayern, Germany
252                                            Germany
262                          Windhoek, Khomas, Namibia
267                     Palma, Balearic Islands, Spain
272                                             London
285                       Paris, Île-de-France, France
298                           Munich, Bavaria, Germany
311                                   Tel Aviv, Israel
316                     Selva, Balearic Islands, Spain
317                      El Paso, Texas, United States
323                   Bad Saarow, Brandenburg, Germany
329                       Paris, Île-de-France, France
357                                       Bodensee, BW
359                                      United States
361                          Hamburg, Hamburg, Germany
368                   Nantes, Pays de la Loire, France
373                        Zurich, Zurich, Switzerland
374                                                 DE
378                                 København, Denmark
387              Mexico City, Distrito Federal, Mexico
390                             London, United Kingdom
403                          Wahlsburg, Hesse, Germany
414                                            Denmark
Name: host_location, dtype: object

In [24]:
listings_filtered['Host_location_berlin']=berlin

### host_response_time + host_response_rate: deal with NaNs (have same amount of Nans)

In [25]:
listings_filtered.host_response_time.value_counts(dropna=False)

NaN                   7122
within an hour        3588
within a day          1472
within a few hours    1342
a few days or more     367
Name: host_response_time, dtype: int64

In [26]:
listings_filtered.host_response_rate.value_counts(dropna=False)

NaN     7122
100%    4516
90%      336
80%      231
0%       211
98%      158
50%      149
67%       90
96%       85
75%       83
60%       75
93%       71
99%       67
86%       60
70%       60
94%       58
83%       54
89%       45
97%       36
33%       35
92%       29
88%       28
40%       27
25%       25
91%       25
62%       20
78%       18
95%       17
71%       16
20%       16
63%       12
57%       12
30%       12
85%        9
44%        9
43%        8
77%        7
82%        6
56%        6
87%        6
73%        5
27%        4
17%        3
10%        3
22%        3
81%        3
69%        2
79%        2
55%        2
14%        2
64%        2
38%        2
58%        2
74%        1
76%        1
72%        1
13%        1
59%        1
29%        1
Name: host_response_rate, dtype: int64

In [27]:
#transfer to numerical
listings_filtered.host_response_rate=listings_filtered.host_response_rate.str.rstrip('%').astype('float')

In [28]:
# a Nan value in reponse rate and time can occur if the client never reached out to the host, or the host never reponsed
#host reponse rate are sometimes zero, so nans are not that the host didnt respond
#this means the client never reached out

In [29]:
#host_response_time Nans= customer never asked something

In [30]:
listings_filtered.host_response_time=listings_filtered.host_response_time.fillna('no request')
listings_filtered.host_response_time.value_counts(dropna=False)

no request            7122
within an hour        3588
within a day          1472
within a few hours    1342
a few days or more     367
Name: host_response_time, dtype: int64

In [31]:
#fill Nans with -1 for binning
listings_filtered.host_response_rate=listings_filtered.host_response_rate.fillna(-1)

In [32]:
listings_filtered.host_response_rate

0         96.0
1         -1.0
2         -1.0
3         -1.0
4         67.0
         ...
13917    100.0
13918    100.0
13919    100.0
13920    100.0
13921    100.0
Name: host_response_rate, Length: 13891, dtype: float64

In [33]:
# bin host_response_rate
rate_labels = ['No request','Low', 'Moderate', 'High']
listings_filtered['host_response_rate_category']=pd.cut(listings_filtered.host_response_rate,[-2,-1,50,80,100],labels=rate_labels)
#data[['IC2','ic2_category_userdef']].head(20)

In [34]:
listings_filtered.host_response_rate_category.value_counts(dropna=False)

No request    7122
High          5609
Moderate       649
Low            511
Name: host_response_rate_category, dtype: int64

In [35]:
#now all nans are indicated as no request and others categorized in different response rates

In [36]:
#drop original reespone rate and time
listings_filtered.dropna(subset = ["host_response_rate"], inplace=True)
listings_filtered.dropna(subset = ["host_response_time"], inplace=True)

In [37]:
listings_filtered.neighbourhood.value_counts(dropna=False)#bascially majority berlin, few detailed once, add column to drop list

Berlin, Germany                                7769
NaN                                            6073
Berlin - Mitte, Germany                           3
Potsdam, Brandenburg, Germany                     3
Berlin , Germany                                  3
Weissensee, Berlin, Germany                       2
Germany                                           2
Berlin, Be, Germany                               2
Berlin, Berlin, DE, Berlin, Germany               2
Glienicke/Nordbahn, Brandenburg, Germany          1
Friedrichshain, Berlin, Germany                   1
Berlin, DE                                        1
Weissenhoher Strasse 14, Berlin, Germany          1
Baseler Straße 91 A,12205 Berlin, Germany         1
Berlin, TH, Germany                               1
Schönefeld, Brandenburg, Germany                  1
Berlin Prenzlauer Berg , Berlin, Germany          1
柏林, Germany                                       1
Berlin- Charlottenburg, Berlin, Germany           1
Prenzlauer Berg, Berlin, Germany                  1
Schöneiche bei Berlin, Brandenburg, Germany       1
Berlin, neukoelln, Germany                        1
Berlin - Schöneberg, Berlin, Germany              1
Berlin Friedrichshain, Berlin, Germany            1
Berlin, Germany, Germany                          1
Берлин, Berlin, Germany                           1
Baseler Straße 91 A, 12205 Berlin , Germany       1
Hoppegarten, Brandenburg, Germany                 1
berlin, Berlin, Germany                           1
Berlin, Zehlendorf, Germany                       1
Berlin-Wedding, Berlin, Germany                   1
Berlin, SN, Germany                               1
Berlin-Mitte, Berlin, Germany                     1
Berlin-Kreuzberg, Berlin, Germany                 1
Berlin, schmargendorf, Germany                    1
Köpenick, Berlin, Germany                         1
Mitte, Berlin, Germany                            1
Berlin, Berlín, Germany                           1
Berlin, Friedrichshain, Germany                   1
Hennigsdorf, Brandenburg, Germany                 1
Mitte/Tiergarten, Berlin, Germany                 1
Name: neighbourhood, dtype: int64

### bathrooms_text: deal with NaNs, create new columns bathroom type and quantity

In [38]:
listings_filtered.bathrooms_text.value_counts(dropna=False)

1 bath               7824
1 shared bath        3435
1 private bath        660
1.5 baths             616
2 baths               580
1.5 shared baths      362
2 shared baths        171
2.5 baths              86
3 baths                30
0 shared baths         24
Half-bath              20
2.5 shared baths       19
0 baths                14
Shared half-bath       12
4 baths                 8
NaN                     8
3.5 baths               4
4.5 shared baths        3
4.5 baths               3
8.5 shared baths        3
7 baths                 2
Private half-bath       2
3 shared baths          2
5 baths                 1
7.5 baths               1
8 baths                 1
Name: bathrooms_text, dtype: int64

In [39]:
#we only have 8 Nans(drop those)
listings_filtered.dropna(subset = ["bathrooms_text"], inplace=True)

In [40]:
# split this into two seperate columns: type of bath room (private, shared) & number of bathrooms (float)

In [41]:
#0 shared baths add to 1 private bath
listings_filtered["bathrooms_text"] = listings_filtered["bathrooms_text"].str.replace('0 shared baths','1 private bath')
#0 baths add to 1 shared bath
listings_filtered["bathrooms_text"] = listings_filtered["bathrooms_text"].str.replace('0 baths','1 shared bath')

In [42]:
#add half-bath to 1 shared bath (because whats half a bath, could mean shared)
listings_filtered["bathrooms_text"] = listings_filtered["bathrooms_text"].str.replace('Half-bath','1 shared bath')

In [43]:
#shared half-bath add to 1 shared bath
listings_filtered["bathrooms_text"] = listings_filtered["bathrooms_text"].str.replace('Shared half-bath','1 shared bath')

In [44]:
#private half-bath add to 1 private
listings_filtered["bathrooms_text"] = listings_filtered["bathrooms_text"].str.replace('Private half-bath','1 private bath')

In [45]:
#find out what most frequent categroy 1 bath means is it private or shared
listings_filtered['property_type'].loc[listings_filtered['bathrooms_text'].str.contains("1 bath", case=False)].head(20)

0               Entire guesthouse
1              Entire rental unit
4              Entire rental unit
5      Entire condominium (condo)
6              Entire rental unit
7                     Entire loft
8              Entire rental unit
9              Entire rental unit
10             Entire rental unit
11     Entire condominium (condo)
13             Entire rental unit
14             Entire rental unit
15             Entire rental unit
16             Entire rental unit
17             Entire rental unit
18             Entire rental unit
23             Entire rental unit
24           Private room in loft
26    Private room in rental unit
28             Entire rental unit
Name: property_type, dtype: object

In [46]:
#seems like entire place is rented therefore its a private bathroom
listings_filtered["bathrooms_text"] = listings_filtered["bathrooms_text"].str.replace('1 private bath','1 bath')

In [47]:
listings_filtered.bathrooms_text.value_counts(dropna=False)

1 bath              8510
1 shared bath       3481
1.5 baths            616
2 baths              580
1.5 shared baths     362
2 shared baths       171
2.5 baths             86
3 baths               30
2.5 shared baths      19
4 baths                8
3.5 baths              4
8.5 shared baths       3
4.5 shared baths       3
4.5 baths              3
7 baths                2
3 shared baths         2
8 baths                1
7.5 baths              1
5 baths                1
Name: bathrooms_text, dtype: int64

In [48]:
#if second splitted string is 'shared' put it into category shared
#otherwise its private catgeory

def clean_bath(x):
    if x.split(" ")[1]=='shared':
        return 'shared'
    else:
        return 'private'

In [49]:
listings_filtered['bathrooms_type']=list(map(clean_bath, listings_filtered['bathrooms_text']))

In [50]:
#get bathroom quantity and put it in a column
listings_filtered["bathroom_qty"] = listings_filtered["bathrooms_text"].str.split(" ", expand=True)[0]

In [51]:
listings_filtered[['bathrooms_text','bathrooms_type','bathroom_qty']].head(15)

   bathrooms_text bathrooms_type bathroom_qty
0          1 bath        private            1
1          1 bath        private            1
2   1 shared bath         shared            1
3       2.5 baths        private          2.5
4          1 bath        private            1
5          1 bath        private            1
6          1 bath        private            1
7          1 bath        private            1
8          1 bath        private            1
9          1 bath        private            1
10         1 bath        private            1
11         1 bath        private            1
12      2.5 baths        private          2.5
13         1 bath        private            1
14         1 bath        private            1

In [52]:
#drop original bathroom text column
listings_filtered.dropna(subset = ["bathrooms_text"], inplace=True)

### bedrooms and beds: deal with NaNs

In [53]:
listings_filtered.bedrooms.value_counts(dropna=False)

1.0     10134
2.0      1956
NaN      1126
3.0       506
4.0       113
5.0        31
6.0        11
7.0         3
9.0         1
8.0         1
12.0        1
Name: bedrooms, dtype: int64

In [54]:
#which airbnbs would contain zero bedrooms which could explain the NaNs
listings_filtered[listings_filtered['bedrooms'].isnull()].property_type.value_counts()

Entire rental unit                     747
Private room in rental unit            142
Entire serviced apartment               66
Entire loft                             51
Entire condominium (condo)              35
Room in hotel                           18
Private room in guesthouse               8
Private room in condominium (condo)      8
Entire guest suite                       8
Private room in residential home         6
Private room in townhouse                5
Private room in guest suite              4
Entire guesthouse                        3
Entire residential home                  3
Room in aparthotel                       3
Private room in hostel                   3
Private room in loft                     3
Room in boutique hotel                   2
Private room in bed and breakfast        2
Tiny house                               2
Entire place                             2
Private room in serviced apartment       2
Entire bungalow                          1
Treehouse                                1
Camper/RV                                1
Name: property_type, dtype: int64

In [55]:
listings_filtered[listings_filtered['bedrooms'].isnull()].room_type.value_counts()

Entire home/apt    922
Private room       204
Name: room_type, dtype: int64

In [56]:
listings_filtered[listings_filtered['bedrooms'].isnull()].accommodates.value_counts()

2     734
3     145
1     123
4     111
5       6
6       5
15      1
16      1
Name: accommodates, dtype: int64

In [57]:
# it could be that the listing has no seperate bedroom but its a studio or a loft 
#or a privatze room where the bed is not a sperate room
#there Nans are zeros
listings_filtered.bedrooms=listings_filtered.bedrooms.fillna('0')

In [58]:
listings_filtered.beds.value_counts(dropna=False)

1.0     8239
2.0     3340
3.0     1040
4.0      533
NaN      224
5.0      199
6.0      158
7.0       49
8.0       41
9.0       20
10.0      16
11.0       7
12.0       6
14.0       4
15.0       2
13.0       2
17.0       1
22.0       1
16.0       1
Name: beds, dtype: int64

In [59]:
# now which listing would not have a bed?

In [60]:
listings_filtered[listings_filtered['beds'].isnull()].property_type.value_counts()

Private room in rental unit            115
Entire rental unit                      65
Entire serviced apartment               10
Entire condominium (condo)               9
Entire loft                              4
Shared room in rental unit               4
Private room in serviced apartment       3
Private room in condominium (condo)      3
Room in boutique hotel                   2
Private room                             1
Entire residential home                  1
Private room in bed and breakfast        1
Room in hotel                            1
Shared room in hostel                    1
Houseboat                                1
Private room in residential home         1
Entire home/apt                          1
Private room in townhouse                1
Name: property_type, dtype: int64

In [61]:
listings_filtered[listings_filtered['beds'].isnull()].accommodates.value_counts()

2    149
1     44
4     14
3     13
6      3
5      1
Name: accommodates, dtype: int64

In [62]:
#since the Nans mostly accomodate 2 persons Nans are filled with being equal to one bed

In [63]:
listings_filtered.beds=listings_filtered.beds.fillna('1')

### deal with several review score columns with NaNs

In [64]:
#review_scores_accuracy   review_scores_cleanliness    review_scores_checkin
#review_scores_communication  review_scores_location   review_scores_value

In [65]:
# listings with zero reviews are already filtered out earlier
#the number of nans in all these columns is quite low

In [66]:
# this would be the overall rating
listings_filtered.review_scores_rating.describe()

count    13883.000000
mean         4.628600
std          0.797593
min          0.000000
25%          4.610000
50%          4.850000
75%          5.000000
max          5.000000
Name: review_scores_rating, dtype: float64

In [67]:
#it could be that some who gave a review didnt fill out the detail ratings for cleaniness, check in and so on
#fill Nans in those detailed despction with the mean of the overall rating

In [68]:
listings_filtered.review_scores_cleanliness.describe()
#ratings go from zero to 5
#ad here its very similar to the overall rating already

count    13582.000000
mean         4.640412
std          0.519363
min          0.000000
25%          4.500000
50%          4.800000
75%          5.000000
max          5.000000
Name: review_scores_cleanliness, dtype: float64

In [69]:
for col in listings_filtered[['review_scores_accuracy','review_scores_cleanliness','review_scores_checkin','review_scores_communication','review_scores_location','review_scores_value']]:
    listings_filtered[col] = listings_filtered[col].fillna(listings_filtered.review_scores_rating.median())

In [70]:
listings_filtered[['review_scores_accuracy','review_scores_cleanliness']]

       review_scores_accuracy  review_scores_cleanliness
0                        4.79                       4.52
1                        4.68                       4.53
2                        4.85                       4.90
3                        5.00                       5.00
4                        5.00                       4.84
...                       ...                        ...
13917                    5.00                       5.00
13918                    5.00                       5.00
13919                    5.00                       5.00
13920                    5.00                       5.00
13921                    3.00                       4.00

[13883 rows x 2 columns]

### deal with NaN columns that are completely dropped

In [71]:
listings_filtered.drop(drop_list, axis=1,inplace=True)
drop_list

['name',
 'description',
 'neighborhood_overview',
 'host_about',
 'bathrooms',
 'calendar_updated',
 'license',
 'host_acceptance_rate',
 'host_neighbourhood',
 'neighbourhood']

In [72]:
nulls_percent_df = pd.DataFrame(listings_filtered.isna().sum()/len(listings_filtered)).reset_index()
nulls_percent_df.columns = ['column_name', 'nulls_percentage']
nulls_percent_df.T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68
column_name,id,listing_url,scrape_id,last_scraped,picture_url,host_id,host_url,host_name,host_since,host_location,host_response_time,host_response_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,Host_location_germany,Host_location_berlin,host_response_rate_category,bathrooms_type,bathroom_qty
nulls_percentage,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#all NaNs are gone

### drop some unnecessary columns

In [74]:
listings_filtered.head(5)

,id,listing_url,scrape_id,last_scraped,picture_url,host_id,host_url,host_name,host_since,host_location,host_response_time,host_response_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,Host_location_germany,Host_location_berlin,host_response_rate_category,bathrooms_type,bathroom_qty
0,2015,https://www.airbnb.com/rooms/2015,20211217003618,2021-12-17,https://a0.muscache.com/pictures/260fd609-710a...,2217,https://www.airbnb.com/users/show/2217,Ion,2008-08-18,"Key Biscayne, Florida, United States",within an hour,96.0,t,https://a0.muscache.com/im/pictures/user/21428...,https://a0.muscache.com/im/pictures/user/21428...,5.0,5.0,['email'],t,f,Brunnenstr. Süd,Mitte,52.53305,13.40394,Entire guesthouse,Entire home/apt,2,1 bath,1.0,2.0,"[""Essentials"", ""Heating"", ""Backyard"", ""Long te...",$53.00,90,1125,2.0,90.0,1125.0,1125.0,84.3,1125.0,t,28,58,64,326,2021-12-17,144,10,0,2016-04-11,2021-11-02,4.66,4.79,4.52,4.88,4.90,4.96,4.58,f,4,4,0,0,2.08,False,False,High,private,1
1,3176,https://www.airbnb.com/rooms/3176,20211217003618,2021-12-17,https://a0.muscache.com/pictures/243355/84afcf...,3718,https://www.airbnb.com/users/show/3718,Britta,2008-10-19,"Coledale, New South Wales, Australia",no request,-1.0,f,https://a0.muscache.com/im/users/3718/profile_...,https://a0.muscache.com/im/users/3718/profile_...,1.0,1.0,"['email', 'phone', 'facebook', 'reviews', 'man...",t,t,Prenzlauer Berg Südwest,Pankow,52.53471,13.41810,Entire rental unit,Entire home/apt,4,1 bath,1.0,2.0,"[""Essentials"", ""Heating"", ""Smoke alarm"", ""Iron...",$90.00,92,1125,92.0,92.0,1125.0,1125.0,92.0,1125.0,t,0,0,0,170,2021-12-17,147,1,0,2009-06-20,2021-01-01,4.63,4.68,4.53,4.64,4.69,4.92,4.63,f,1,1,0,0,0.97,False,False,No request,private,1
2,7071,https://www.airbnb.com/rooms/7071,20211217003618,2021-12-17,https://a0.muscache.com/pictures/21278/32a1622...,17391,https://www.airbnb.com/users/show/17391,BrightRoom,2009-05-16,"Berlin, Berlin, Germany",no request,-1.0,t,https://a0.muscache.com/im/pictures/user/48c3d...,https://a0.muscache.com/im/pictures/user/48c3d...,2.0,2.0,"['email', 'phone', 'reviews', 'jumio', 'govern...",t,t,Helmholtzplatz,Pankow,52.54301,13.41534,Private room in rental unit,Private room,2,1 shared bath,1.0,2.0,"[""Essentials"", ""Heating"", ""Refrigerator"", ""Hai...",$33.00,1,10,1.0,1.0,10.0,10.0,1.0,10.0,t,0,0,0,0,2021-12-17,293,0,0,2009-08-18,2020-03-31,4.83,4.85,4.90,4.86,4.85,4.91,4.71,t,1,0,1,0,1.95,True,True,No request,shared,1
3,9991,https://www.airbnb.com/rooms/9991,20211217003618,2021-12-17,https://a0.muscache.com/pictures/42799131/59c8...,33852,https://www.airbnb.com/users/show/33852,Philipp,2009-08-25,"Berlin, Berlin, Germany",no request,-1.0,f,https://a0.muscache.com/im/users/33852/profile...,https://a0.muscache.com/im/users/33852/profile...,1.0,1.0,['email'],t,t,Prenzlauer Berg Südwest,Pankow,52.53269,13.41805,Entire rental unit,Entire home/apt,7,2.5 baths,4.0,7.0,"[""Essentials"", ""Children\u2019s dinnerware"", ""...",$180.00,6,14,6.0,6.0,14.0,14.0,6.0,14.0,t,0,0,0,0,2021-12-17,8,0,0,2015-08-09,2020-01-04,5.00,5.00,5.00,5.00,5.00,4.86,4.86,f,1,1,0,0,0.10,True,True,No request,private,2.5
4,14325,https://www.airbnb.com/rooms/14325,20211217003618,2021-12-17,https://a0.muscache.com/pictures/508703/24988a...,55531,https://www.airbnb.com/users/show/55531,Chris + Oliver,2009-11-18,"Berlin, Berlin, Germany",within a day,67.0,t,https://a0.muscache.com/im/users/55531/profile...,https://a0.muscache.com/im/users/55531/profile...,4.0,4.0,"['email', 'work_email']",t,t,Prenzlauer Berg Nordwest,Pankow,52.54813,13.40366,Entire rental unit,Entire home/apt,1,1 bath,0,1.0,"[""Ethernet connection"", ""Heating"", ""Coffee mak...",$70.00,95,1125,95.0,95.0,1125.0,1125.0,95.0,1125.0,t,19,19,19,159,2021-12-17,26,1,0,2010-06-29,2021-06-21,4.67,5.00,4.84,4.68,4.84,4.58,4.42,f,3,3,0,0,0.19,True,True,Moderate,private,1

In [77]:
#host_listings_count, host_total_listings_count are indentical

In [78]:
drop_list2=['scrape_id','last_scraped','picture_url','host_name','host_thumbnail_url','host_picture_url', 'host_total_listings_count','bathrooms_text','calendar_last_scraped']
listings_filtered.drop(drop_list2, axis=1,inplace=True)
listings_filtered.shape

(13883, 60)

In [79]:
listings_filtered.to_csv('listings_berlin_null_free.csv',index=False)